baseURL = "https://stoxproject.github.io"
languageCode = "en-us"
title = "StoX Project Homepage"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "StoX Project Team at the Institute of Marine Research, Norway"
    description = "An open source approach to acoustic and swept area survey calculations"
    githubUsername = "StoXProject"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["R", "C++", "JavaScript", "TypeScript"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:stox@hi.no"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/StoXProject/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.hi.no/hi/forskning/prosjekter/stox"
    name = "level-up"
    weight = 3

